### ISSUE TITLE
Minishift Permission denied: '/var/opt/redislabs/log/supervisord.log' .

### ISSUE THREAD

**Issue by ripper2hl** [RedisLabs/redis-enterprise-k8s-docs#120]
When i tried to deploy redis enterpirse on minishift i have this error.
```log 

e is 65537 (0x10001)
Signature ok
subject=/CN=redis-enterprise-0.redis-enterprise.redislab7.svc.cluster.local/OU=Admin UI/O=RedisLabs Enterprise Cluster
Getting Private key
Run command: ['/opt/redislabs/sbin/generate_cert.sh', 'syncer', 'syncer']
Run command: ['/opt/redislabs/sbin/generate_cert.sh', 'metrics_exporter', 'metrics_exporter']
Run command: ['/opt/redislabs/sbin/generate_cert.sh', 'api', 'Cluster API']
Run command: ['/opt/redislabs/sbin/generate_cert.sh', 'proxy', 'redisdb']
Run command: ['/opt/redislabs/sbin/generate_cert.sh', 'cm', 'Admin UI']
Done.
Traceback (most recent call last):
  File "//opt/redislabs/bin/supervisord", line 9, in <module>
    sys.exit(load_entry_point('supervisor', 'console_scripts', 'supervisord')())
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/supervisord.py", line 363, in main
    go(options)
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/supervisord.py", line 373, in go
    d.main()
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/supervisord.py", line 78, in main
    info_messages)
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/options.py", line 1406, in make_logger
    stdout = self.nodaemon,
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/opt/redislabs/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/var/opt/redislabs/log/supervisord.log'
2020-05-14 17:58:47,292 INFO __main__ MainThread: Waiting for REST API to be accessible
2020-05-14 18:04:51,633 ERROR __main__ MainThread: wait for api exhausted
2020-05-14 18:04:51,634 INFO __main__ MainThread: Done, moving to bootstrapping
2020-05-14 18:04:51,634 INFO __main__ MainThread: Bootstrapping node with action 'None'
2020-05-14 18:04:51,635 INFO __main__ MainThread: Done
``` 

This is the `redis-enterprise-cluster_rhel.yaml`

```yml
apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "" # ! edit according to infrastructure
  uiServiceType: LoadBalancer
  username: "demo@redislabs.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "4000m"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/redis
    versionTag:       5.4.14-31.rhel7-openshift
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller
    versionTag:       5.4.14-7.rhel7
  bootstrapperImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/operator
    versionTag:       5.4.14-7.rhel7

```

This is the `openshift.bundle.yaml`

```
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: redis-enterprise-scc
allowPrivilegedContainer: false
allowedCapabilities:
  - SYS_RESOURCE
runAsUser:
  type: MustRunAs
  uid: 1001
FSGroup:
  type: MustRunAs
  ranges: 1001,1001
seLinuxContext:
  type: RunAsAny
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator-sb
rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["clusterservicebrokers"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
rules:
  - apiGroups: ["rbac.authorization.k8s.io", ""]
    resources: ["roles", "serviceaccounts", "rolebindings"]
    verbs: ["*"]
  - apiGroups:
      - app.redislabs.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "delete", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get" , "update", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get" , "update"]

  # needed rbac rules for services controller
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "update", "patch", "create", "delete"]
  - apiGroups:
      - route.openshift.io
    resources: ["routes", "routes/custom-host"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames:
      - redis-enterprise-psp
    verbs:
      - use
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-enterprise-operator
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
subjects:
- kind: ServiceAccount
  name: redis-enterprise-operator
roleRef:
  kind: Role
  name: redis-enterprise-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseclusters.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseCluster
    listKind: RedisEnterpriseClusterList
    plural: redisenterpriseclusters
    singular: redisenterprisecluster
    shortNames:
      - rec
  subresources:
    status: {}
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: false
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-enterprise-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-enterprise-operator
  template:
    metadata:
      labels:
        name: redis-enterprise-operator
    spec:
      serviceAccount: redis-enterprise-operator
      containers:
        - name: redis-enterprise-operator
          image:  redislabs/operator:5.4.14-7.rhel7
          securityContext:
            runAsUser: 1001
          command:
          - redis-enterprise-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---

```

![Captura de pantalla de 2020-05-14 13-23-44](https://user-images.githubusercontent.com/2611201/81971185-4e7c3100-95e6-11ea-9592-fa3a8d05379e.png)

Some information of minishift:

```bash
minishift addons list
- admin-user			 : enabled	P(0)
- anyuid			 : enabled	P(0)
- admissions-webhook		 : disabled	P(0)
- che				 : disabled	P(0)
- htpasswd-identity-provider	 : disabled	P(0)
- redhat-registry-login		 : disabled	P(0)
- registry-route		 : disabled	P(0)
- xpaas				 : disabled	P(0)


$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+d699176-406)
DiskUsage:  42% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.703 GB (used by oc binary, ISO or cached images)

```

**Comment by pescarcena** [comment]
Hello, 
Please execute:
```
oc get pv
oc get pvc
```

**Comment by amiramm** [comment]
@ripper2hl Minishift is a single node K8s cluster. You are trying to deploy a three-node Redis Enterprise cluster that uses anti-affinity rules which prevents more than one statefulset pod to be scheduled on the same node. You can try to reduce the number of nodes to 1. I would also check the resource requirements to make sure they fit within your Minishift available resources otherwise you'll need to assign Minishift additional RAM and CPU resources.
