### ISSUE TITLE
Istio CSRF error

### ISSUE THREAD

**Issue by 2ZZ** [RedisLabs/redis-enterprise-k8s-docs#121]
I am attempting to expose the Redis Enterprise UI in an Istio enabled EKS cluster. 
The UI page loads correctly but attempting to login fails with a 400 Bad Request.
Digging into the logs I can see the flask_wtf python package isn't happy with the CSRF token.
```
==> /var/opt/redislabs/log/cm_server.log <==
2020-05-20 14:15:40,919 WARNING flask.app Thread-39: Request resulted in 400 Bad Request: CSRF token missing or incorrect.
Traceback (most recent call last):
  File "/opt/redislabs/lib/python2.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/redislabs/lib/python2.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/opt/redislabs/lib/python2.7/site-packages/flask_wtf/csrf.py", line 178, in _csrf_protect
    return self._error_response(reason)
  File "/opt/redislabs/lib/python2.7/site-packages/flask_wtf/csrf.py", line 212, in _error_response
    return abort(400, reason)
  File "/opt/redislabs/lib/python2.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/opt/redislabs/lib/python2.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
BadRequest: 400 Bad Request: CSRF token missing or incorrect.
```
Checking a packet capture the Envoy proxy in Istio is setting the CSRF token header to lowercase before it reaches the app. I've tried without success to turn that functionality off in Istio, but the case of a header should be ignored according to HTTP spec.
![image](https://user-images.githubusercontent.com/5006129/82468017-3e6ac280-9aba-11ea-8319-9165e5ec1ff8.png)
In `/opt/redislabs/lib/python2.7/site-packages/flask_wtf/csrf.py` it is specifically checking for uppercase.
```
            if not csrf_token:
                # You can get csrf token from header
                # The header name is the same as Django
                csrf_token = request.headers.get('X-CSRFToken')
            if not csrf_token:
                # The header name is the same as Rails
                csrf_token = request.headers.get('X-CSRF-Token')
            if not validate_csrf(csrf_token):
                reason = 'CSRF token missing or incorrect.'
                return self._error_response(reason)
```

In newer versions of flask_wtf it is possible to change the field name `https://flask-wtf.readthedocs.io/en/stable/config.html#configuration`

Would it be possible to either allow us to change the header name, or toggle the CSRF check off via a config variable?

**Comment by amiramm** [comment]
Hi @2ZZ , please open a case with Redis Labs support support@redislabs.com and we'll take it from there.

**Comment by amiramm** [comment]
Issue is handled by RedisLabs support.
