### ISSUE TITLE
Error on cluster startup.

### ISSUE THREAD

**Issue by WilliamCassanova** [RedisLabs/redis-enterprise-k8s-docs#30]
When attempting to instantiate an instance of the operator on the ibm cloud. I am seeing the following error. 

```ERROR root MainThread: Error running rladmin, output=Creating a new cluster... error: [path_error] Failed to access directory /opt/persistent
Traceback (most recent call last):
  File "/opt/bootstrap.py", line 123, in create_cluster
    'password', password] + additional_args + ['json_file', BOOTSTRAP_FILE_PATH])
  File "/opt/redislabs/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/opt/redislabs/bin/rladmin', 'cluster', 'create', 'name', 'redis-enterprise.sun-location-ingestor-dev.svc.cluster.local', 'username', 'admin@acme.com', 'password', 'vMTJl3uk', 'persistent_path', '/opt/persistent', 'json_file', '/tmp/bootstrap_params.json']' returned non-zero exit status 1
2019-03-14 17:17:29,032 INFO __main__ MainThread: Failed, Exiting.
```
My redis-enterprise-cluster.yaml is as follows:
```
apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  persistentSpec:
    enabled: True
    storageClassName: "ibmc-file-custom" # ! edit according to infrastructure
  uiServiceType: LoadBalancer
  username: "admin@acme.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "4000m"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/redis
    versionTag:       5.4.0-19
```
ibm-file custom is a valid option as shown below;
```
kubectl get StorageClasses
NAME                         PROVISIONER        AGE
default                      ibm.io/ibmc-file   6d
ibmc-file-bronze (default)   ibm.io/ibmc-file   6d
ibmc-file-custom             ibm.io/ibmc-file   6d
ibmc-file-gold               ibm.io/ibmc-file   6d
ibmc-file-retain-bronze      ibm.io/ibmc-file   6d
ibmc-file-retain-custom      ibm.io/ibmc-file   6d
ibmc-file-retain-gold        ibm.io/ibmc-file   6d
ibmc-file-retain-silver      ibm.io/ibmc-file   6d
ibmc-file-silver             ibm.io/ibmc-file   6d
```

**Comment by danni-m** [comment]
@WilliamCassanova Hi, sorry for the late response, can you give more log context here?
If its easier you can contact our support with the issue details.

**Comment by danni-m** [comment]
@WilliamCassanova closing, if you still have issues please reopen.
